typography_spectrum: 1
content_rating:
  adult: false
color:
  brandStrength: 0.4211117535776984
  lightness: 0.4227826667860113
  saturation: 0.1933886461601694
  rhythmicContrast: 0.6171339075439748
  brandColors:
    - '#000000'
    - '#FEFEFE'
    - '#CA3F01'
    - '#FDE03A'
    - '#776D75'
github: true
opengraph: {}
layout_spectrum: 0.03020157646544573
analytics: {}
author: {}
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6d759224-e2ae-4dbb-b166-36adc8dbe232.jpg
name: Beerhouse
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: 'About '
    url: 'http://beerhouse.teachable.com/about/'
    type: external
  - name: Blog
    url: 'http://beerhouse.teachable.com/blog/'
    type: external
  - name: Contact
    url: 'http://beerhouse.teachable.com/contact/'
    type: external
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Beerhouse Education
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c1501e2b-5a96-4a19-b730-b33ef0f391b3.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c1501e2b-5a96-4a19-b730-b33ef0f391b3.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        favicon: null
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Tap into the Business of Craft Beer '
purpose:
  - type: external
    url: 'http://beerhouse.teachable.com'
    label: FREE! Mini-Course
