content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c1501e2b-5a96-4a19-b730-b33ef0f391b3.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c1501e2b-5a96-4a19-b730-b33ef0f391b3.jpg
    metadata:
      description: ''
      '@context': 'http://schema.org'
      related: []
      author: []
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        favicon: null
      app_links: []
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Tap into the Business of Craft Beer '
title: Beerhouse Education Center
content_rating:
  adult: false
navigation:
  - name: 'About '
    url: 'http://beerhouse.teachable.com/about/'
    type: external
  - name: Blog
    url: 'http://beerhouse.teachable.com/blog/'
    type: external
  - name: Contact
    url: 'http://beerhouse.teachable.com/contact/'
    type: external
  - name: Photo
    url: 'http://beerhouse.photo'
    type: external
layout_spectrum: 0.1767895462570509
github: true
author: {}
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Beerhouse
analytics: {}
opengraph: {}
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  brandStrength: 0.1851145770029156
  lightness: 0.825105119138624
  saturation: 0.6763984835598765
  rhythmicContrast: 0.9155827533867726
  brandColors:
    - '#000000'
    - '#FEFEFE'
    - '#CA3F01'
    - '#FDE03A'
    - '#776D75'
typography_spectrum: 0.7602691148074878
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6d759224-e2ae-4dbb-b166-36adc8dbe232.jpg
